# -*- coding: utf-8 -*-
"""hello_world.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/mlcc/hello_world.ipynb

#### Copyright 2017 Google LLC.
"""

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""# Prework: Hello World

**Learning Objective:** Run a TensorFlow program in the browser.

The code block below is a "Hello World" TensorFlow program.

It consists of initialization code (importing tensorflow module and enabling "eager execution", which will be covered in more detail in subsequent exercises) and printing a "Hello, world!" string constant.
"""

from __future__ import print_function

import tensorflow as tf
try:
  tf.contrib.eager.enable_eager_execution()
except ValueError:
  pass  # enable_eager_execution errors after its first call

tensor = tf.constant('Hello, world!')
tensor_value = tensor.numpy()
print(tensor_value)

"""## To Run This Program

  1. Click anywhere in the code block (for example, on the word `import`).

  2. Click the right-facing-triangle icon in the upper-left corner of the code block, or hit ⌘/Ctrl-Enter.

     The program will take a few seconds to run. If all goes well, the program will write the phrase `Hello, world!` just below the code block

This entire program consists of a single code block. However, most exercises consist of multiple code blocks, in which case you should **run the code blocks individually in sequence, from top to bottom.** 

Running the code blocks out of sequence typically causes errors.

## Useful Keyboard Shortcuts

* **⌘/Ctrl+m,b:** creates an empty code cell below the cell that's currently selected
* **⌘/Ctrl+m,i:** interrupts a running cell
* **⌘/Ctrl+m,h:** shows a list of all keyboard shortcuts
* For documentation on any TensorFlow API method, place the cursor right after its opening parenthesis and hit **Tab**:

  ![pop-up documentation for TensorFlow tf.constant method](https://download.mlcc.google.com/mledu-images/tf_pop_up_doc_example.png)
"""